package ru.terra.dentist.orm.entity;
// Generated 08.04.2012 2:29:50 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Appointment generated by hbm2java
 */
@Entity
@Table(name = "appointment", catalog = "dentist")
public class Appointment implements java.io.Serializable
{
    private int appId;
    private Patient patient;
    private Diagnosis diagnosis;
    private Comment comment;
    private Date appDate;

    public Appointment()
    {
    }

    public Appointment(int appId, Patient patient, Diagnosis diagnosis, Comment comment)
    {
	this.appId = appId;
	this.patient = patient;
	this.diagnosis = diagnosis;
	this.comment = comment;
    }

    public Appointment(int appId, Patient patient, Diagnosis diagnosis, Comment comment, Date appDate)
    {
	this.appId = appId;
	this.patient = patient;
	this.diagnosis = diagnosis;
	this.comment = comment;
	this.appDate = appDate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "app_id", unique = true, nullable = false)
    public int getAppId()
    {
	return this.appId;
    }

    public void setAppId(int appId)
    {
	this.appId = appId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pat_id", nullable = false)
    public Patient getPatient()
    {
	return this.patient;
    }

    public void setPatient(Patient patient)
    {
	this.patient = patient;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "diag_id", nullable = false)
    public Diagnosis getDiagnosis()
    {
	return this.diagnosis;
    }

    public void setDiagnosis(Diagnosis diagnosis)
    {
	this.diagnosis = diagnosis;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "comment_id", nullable = false)
    public Comment getComment()
    {
	return this.comment;
    }

    public void setComment(Comment comment)
    {
	this.comment = comment;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "app_date", length = 10)
    public Date getAppDate()
    {
	return this.appDate;
    }

    public void setAppDate(Date appDate)
    {
	this.appDate = appDate;
    }
}
