package ru.terra.dentist.orm.entity;
// Generated 26.01.2012 19:42:07 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppointmentId generated by hbm2java
 */
@Embeddable
public class AppointmentId implements java.io.Serializable
{

    private int appId;
    private int patId;
    private int diagId;
    private int commentId;

    public AppointmentId()
    {
    }

    public AppointmentId(int appId, int patId, int diagId, int commentId)
    {
        this.appId = appId;
        this.patId = patId;
        this.diagId = diagId;
        this.commentId = commentId;
    }

    @Column(name = "app_id", nullable = false)
    public int getAppId()
    {
        return this.appId;
    }

    public void setAppId(int appId)
    {
        this.appId = appId;
    }

    @Column(name = "pat_id", nullable = false)
    public int getPatId()
    {
        return this.patId;
    }

    public void setPatId(int patId)
    {
        this.patId = patId;
    }

    @Column(name = "diag_id", nullable = false)
    public int getDiagId()
    {
        return this.diagId;
    }

    public void setDiagId(int diagId)
    {
        this.diagId = diagId;
    }

    @Column(name = "comment_id", nullable = false)
    public int getCommentId()
    {
        return this.commentId;
    }

    public void setCommentId(int commentId)
    {
        this.commentId = commentId;
    }

    public boolean equals(Object other)
    {
        if ((this == other))
        {
            return true;
        }
        if ((other == null))
        {
            return false;
        }
        if (!(other instanceof AppointmentId))
        {
            return false;
        }
        AppointmentId castOther = (AppointmentId) other;

        return (this.getAppId() == castOther.getAppId())
                && (this.getPatId() == castOther.getPatId())
                && (this.getDiagId() == castOther.getDiagId())
                && (this.getCommentId() == castOther.getCommentId());
    }

    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getAppId();
        result = 37 * result + this.getPatId();
        result = 37 * result + this.getDiagId();
        result = 37 * result + this.getCommentId();
        return result;
    }
}
