package ru.terra.dentist.orm.entity;
// Generated 08.04.2012 2:29:50 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Diagnosis generated by hbm2java
 */
@Entity
@Table(name = "diagnosis", catalog = "dentist")
public class Diagnosis implements java.io.Serializable
{
    private int diagId;
    private String diagCode;
    private String diagName;
    private Integer diagPrice;
    private Set<Appointment> appointments = new HashSet<Appointment>(0);

    public Diagnosis()
    {
    }

    public Diagnosis(int diagId)
    {
	this.diagId = diagId;
    }

    public Diagnosis(int diagId, String diagCode, String diagName, Integer diagPrice, Set<Appointment> appointments)
    {
	this.diagId = diagId;
	this.diagCode = diagCode;
	this.diagName = diagName;
	this.diagPrice = diagPrice;
	this.appointments = appointments;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "diag_id", unique = true, nullable = false)
    public int getDiagId()
    {
	return this.diagId;
    }

    public void setDiagId(int diagId)
    {
	this.diagId = diagId;
    }

    @Column(name = "diag_code", length = 20)
    public String getDiagCode()
    {
	return this.diagCode;
    }

    public void setDiagCode(String diagCode)
    {
	this.diagCode = diagCode;
    }

    @Column(name = "diag_name", length = 200)
    public String getDiagName()
    {
	return this.diagName;
    }

    public void setDiagName(String diagName)
    {
	this.diagName = diagName;
    }

    @Column(name = "diag_price")
    public Integer getDiagPrice()
    {
	return this.diagPrice;
    }

    public void setDiagPrice(Integer diagPrice)
    {
	this.diagPrice = diagPrice;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "diagnosis")
    public Set<Appointment> getAppointments()
    {
	return this.appointments;
    }

    public void setAppointments(Set<Appointment> appointments)
    {
	this.appointments = appointments;
    }
}
