package ru.terra.dentist.orm.entity;
// Generated 08.04.2012 2:29:50 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", catalog = "dentist")
public class Patient implements java.io.Serializable
{
    private int patId;
    private Integer patNum;
    private String patSurname;
    private String patName;
    private String patMidname;
    private Set<Appointment> appointments = new HashSet<Appointment>(0);

    public Patient()
    {
    }

    public Patient(int patId)
    {
	this.patId = patId;
    }

    public Patient(int patId, Integer patNum, String patSurname, String patName, String patMidname, Set<Appointment> appointments)
    {
	this.patId = patId;
	this.patNum = patNum;
	this.patSurname = patSurname;
	this.patName = patName;
	this.patMidname = patMidname;
	this.appointments = appointments;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "pat_id", unique = true, nullable = false)
    public int getPatId()
    {
	return this.patId;
    }

    public void setPatId(int patId)
    {
	this.patId = patId;
    }

    @Column(name = "pat_num")
    public Integer getPatNum()
    {
	return this.patNum;
    }

    public void setPatNum(Integer patNum)
    {
	this.patNum = patNum;
    }

    @Column(name = "pat_surname", length = 100)
    public String getPatSurname()
    {
	return this.patSurname;
    }

    public void setPatSurname(String patSurname)
    {
	this.patSurname = patSurname;
    }

    @Column(name = "pat_name", length = 100)
    public String getPatName()
    {
	return this.patName;
    }

    public void setPatName(String patName)
    {
	this.patName = patName;
    }

    @Column(name = "pat_midname", length = 100)
    public String getPatMidname()
    {
	return this.patMidname;
    }

    public void setPatMidname(String patMidname)
    {
	this.patMidname = patMidname;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "patient")
    public Set<Appointment> getAppointments()
    {
	return this.appointments;
    }

    public void setAppointments(Set<Appointment> appointments)
    {
	this.appointments = appointments;
    }
}
