package ru.terra.dentist.orm.entity;
// Generated 26.01.2012 19:42:07 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", catalog = "dentist")
public class Patient implements java.io.Serializable
{

    @Id
    @Column(name = "pat_id", unique = true, nullable = false)
    @GeneratedValue(strategy=GenerationType.TABLE)
    private int patId;
    @Column(name = "pat_num")
    private Integer patNum;
    @Column(name = "pat_surname", length = 100)
    private String patSurname;
    @Column(name = "pat_name", length = 100)
    private String patName;
    @Column(name = "pat_midname", length = 100)
    private String patMidname;
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "patient")
    private Set<Appointment> appointments = new HashSet<Appointment>(0);

    public Patient()
    {
    }

    public Patient(int patId)
    {
        this.patId = patId;
    }

    public Patient(int patId, Integer patNum, String patSurname, String patName, String patMidname, Set<Appointment> appointments)
    {
        this.patId = patId;
        this.patNum = patNum;
        this.patSurname = patSurname;
        this.patName = patName;
        this.patMidname = patMidname;
        this.appointments = appointments;
    }

    public int getPatId()
    {
        return this.patId;
    }

    public void setPatId(int patId)
    {
        this.patId = patId;
    }

    public Integer getPatNum()
    {
        return this.patNum;
    }

    public void setPatNum(Integer patNum)
    {
        this.patNum = patNum;
    }

    public String getPatSurname()
    {
        return this.patSurname;
    }

    public void setPatSurname(String patSurname)
    {
        this.patSurname = patSurname;
    }

    public String getPatName()
    {
        return this.patName;
    }

    public void setPatName(String patName)
    {
        this.patName = patName;
    }

    public String getPatMidname()
    {
        return this.patMidname;
    }

    public void setPatMidname(String patMidname)
    {
        this.patMidname = patMidname;
    }

    public Set<Appointment> getAppointments()
    {
        return this.appointments;
    }

    public void setAppointments(Set<Appointment> appointments)
    {
        this.appointments = appointments;
    }
}
